# Generated by Django 4.2 on 2024-08-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='size',
            field=models.CharField(choices=[('LARGE', 'Большое'), ('MEDIUM', 'Среднее'), ('SMALL', 'Маленькое')], default='LARGE', max_length=255, verbose_name='Размер изображения'),
        ),
    ]
