MAX_PAGE_SIZE = 10
MAX_PRODUCT_IMAGES = 3

# Base model fields
NAME_MAX_LENGTH = 255
SLUG_MAX_LENGTH = 255

# Producs models fields
MAX_DIGITS_PRICE = 10
MAX_DECIMAL_PLACES_PRICE = 2
IMAGE_SIZE_MAX_LENGTH = 255
